# Generated by Django 4.1.7 on 2023-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodboard', '0002_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
